### ISSUE TITLE
Kicad Version Problem

### ISSUE THREAD

**Issue by Jotan** [AcheronProject/Anticheww#1]
Hi, 
I want to create my own mech keyboard and i look this project and is very impressive my congrats!!!. I downloaded the kicad project and have the error version and I want to know what version of kicad is made. Thank you so much.

**Comment by Gondolindrim** [comment]
Hey!

I am using the KiCad nightly builds! I forget exactly which was used for Anticheww so assume it uses the latest nightly.

**Comment by Jotan** [comment]
Thank you so much
